### ISSUE TITLE
Triangle example segfaults in glfwTerminate

### ISSUE THREAD

**Issue by silversquirl** [gfx-rs/wgpu-native#144]
Occasionally it's a `corrupted double-linked list` abort rather than a segfault. Running in a debugger gives the following backtrace:
```
Thread 1 "triangle" received signal SIGSEGV, Segmentation fault.
unlink_chunk (p=p@entry=0x40bac0, av=0x7ffff724ba00 <main_arena>) at malloc.c:1471
1471	malloc.c: No such file or directory.
(gdb) bt
#0  unlink_chunk (p=p@entry=0x40bac0, av=0x7ffff724ba00 <main_arena>) at malloc.c:1471
#1  0x00007ffff7113205 in _int_free (av=0x7ffff724ba00 <main_arena>, p=0x40bac0,
    have_lock=<optimized out>) at malloc.c:4366
#2  0x00007ffff6e30858 in _XFreeDisplayStructure () from /usr/lib/libX11.so.6
#3  0x00007ffff6e1dbd1 in XCloseDisplay () from /usr/lib/libX11.so.6
#4  0x00007ffff7f5b79b in ?? () from /usr/lib/libglfw.so.3
#5  0x00007ffff7f52ad4 in ?? () from /usr/lib/libglfw.so.3
#6  0x0000000000401b14 in main () at main.c:266
```

wgpu-native version: abecfdca39aa15160bb1f63dd08bfb5335578375
GLFW version: glfw-3.3.4_1
System info:
```
$ lsb_release -a
LSB Version:	1.0
Distributor ID:	VoidLinux
Description:	Void Linux
Release:	rolling
Codename:	void
$ uname -a
Linux themisto 5.13.13_1 #1 SMP Fri Aug 27 13:28:13 UTC 2021 x86_64 GNU/Linux
```

**Comment by kvark** [comment]
Looks related to https://github.com/gfx-rs/wgpu/issues/318 or https://github.com/gfx-rs/wgpu/issues/515
