### ISSUE TITLE
emscripten support: signature_mismatch for deviceId

### ISSUE THREAD

**Issue by caiiiycuk** [gfx-rs/wgpu-native#169]
In `webgpu.h` device id declared as uint32:
```c
    uint32_t deviceID;
```

But in wgpu-core device id is uint64. Because of that I have warning on linking stage:
```
[100%] Linking C executable triangle.js
wasm-ld: warning: function signature mismatch: wgpuCommandEncoderBeginRenderPass
>>> defined as (i32, i32) -> i32 in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i32) -> i32 in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.2w9kgy3ch2pbb8ch.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuRenderPassEncoderSetPipeline
>>> defined as (i32, i32) -> void in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i32, i64) -> void in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.2w9kgy3ch2pbb8ch.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuDeviceCreateShaderModule
>>> defined as (i32, i32) -> i32 in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i32) -> i64 in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.4ddurkv35348ngag.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuDeviceCreateCommandEncoder
>>> defined as (i32, i32) -> i32 in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i32) -> i64 in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.4ddurkv35348ngag.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuAdapterRequestDevice
>>> defined as (i32, i32, i32, i32) -> void in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i32, i32, i32) -> void in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.4ddurkv35348ngag.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuDeviceSetDeviceLostCallback
>>> defined as (i32, i32, i32) -> void in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i32, i32) -> void in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.2lr7829c0ug7kdcr.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuSwapChainGetCurrentTextureView
>>> defined as (i32) -> i32 in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64) -> i64 in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.4ddurkv35348ngag.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuDeviceSetUncapturedErrorCallback
>>> defined as (i32, i32, i32) -> void in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i32, i32) -> void in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.2lr7829c0ug7kdcr.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuDeviceCreatePipelineLayout
>>> defined as (i32, i32) -> i32 in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i32) -> i64 in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.4ddurkv35348ngag.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuCommandEncoderFinish
>>> defined as (i32, i32) -> i32 in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i32) -> i64 in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.2w9kgy3ch2pbb8ch.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuDeviceCreateRenderPipeline
>>> defined as (i32, i32) -> i32 in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i32) -> i64 in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.4ddurkv35348ngag.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuInstanceCreateSurface
>>> defined as (i32, i32) -> i32 in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i32, i32) -> i64 in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.2lr7829c0ug7kdcr.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuQueueSubmit
>>> defined as (i32, i32, i32) -> void in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i32, i32) -> void in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.4ddurkv35348ngag.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuDeviceGetQueue
>>> defined as (i32) -> i32 in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64) -> i64 in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.4ddurkv35348ngag.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuSwapChainPresent
>>> defined as (i32) -> void in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64) -> void in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.4ddurkv35348ngag.rcgu.o)

wasm-ld: warning: function signature mismatch: wgpuDeviceCreateSwapChain
>>> defined as (i32, i32, i32) -> i32 in CMakeFiles/triangle.dir/main.c.o
>>> defined as (i64, i64, i32) -> i64 in /home/caiiiycuk/rust/wgpu-native/examples/triangle/../../target/wasm32-unknown-emscripten/debug/libwgpu_native.a(wgpu_native.4ddurkv35348ngag.rcgu.o)
```

And error in runtime:
```
triangle.js:35 Uncaught RuntimeError: unreachable
    at signature_mismatch:wgpuInstanceCreateSurface (0ae30422:0x7651)
    at __original_main (0ae30422:0x79eb)
    at main (0ae30422:0x86e6)
    at triangle.js:1542:22
    at callMain (triangle.js:10123:15)
    at doRun (triangle.js:10180:23)
    at triangle.js:10191:7
```

What is the best fix here? Change webgpu.h or wgpu-core? Or something else

**Comment by caiiiycuk** [comment]
Found this in wgpu-core:
```rust
    fn zip(index: Index, epoch: Epoch, backend: Backend) -> Self {
        assert_eq!(0, epoch >> (32 - BACKEND_BITS));
        let v = index as u64 | ((epoch as u64) << 32) | ((backend as u64) << (64 - BACKEND_BITS));
        Id(NonZeroU64::new(v).unwrap(), PhantomData)
    }

    fn unzip(self) -> (Index, Epoch, Backend) {
        (
            self.0.get() as u32,
            (self.0.get() >> 32) as u32 & EPOCH_MASK,
            self.backend(),
        )
    }
```

Does it mean that we can't use 32bits ID? and only way to fix is changing webgpu.h?

**Comment by caiiiycuk** [comment]
can this work?
```rust
impl<T> TypedId for Id<T> {
    #[cfg(feature = "uint32id")]
    fn zip(index: Index, epoch: Epoch, backend: Backend) -> Self {
        assert_eq!(0, epoch >> (16 - BACKEND_BITS));
        if index >> 16 != 0 || epoch >> (16 - BACKEND_BITS) != 0 {
            panic!("Can't zip index {} epoch {} backend {} into 16 bit id", index, epoch, backend as u32);
        }
        let v = index | (epoch << 16) | ((backend as u32) << (32 - BACKEND_BITS));
        Id(NonZeroU32::new(v).unwrap(), PhantomData)
    }

    #[cfg(feature = "uint32id")]
    fn unzip(self) -> (Index, Epoch, Backend) {
        (
            (self.0.get() as u16) as u32,
            (self.0.get() >> 16) & EPOCH_MASK,
            self.backend(),
        )
    }
```

**Comment by kvark** [comment]
@caiiiycuk you are confusing two different things here.
`wgpu_core::id::DeviceId` is a unique identity of a logical device in wgpu's internal storages.

But the `uint32_t deviceID;` is not that. Instead, it's [PCI ID](https://en.wikipedia.org/wiki/PCI_configuration_space) for the device, unrelated to any internals of wgpu.
