### ISSUE TITLE
Can't acquire next swapchain texture after alternating between fullscreen and windowed mode

### ISSUE THREAD

**Issue by radgeRayden** [gfx-rs/wgpu-native#24]
I have edited the triangle example to showcase this:
https://gist.github.com/radgeRayden/548d101bd7b83e4366a413789866e90a
It only takes a few alternations to break it. Doesn't need to be very fast. If I move the swapchain re-creation code to the window resized callback, it seems to not happen under AMD, only intel. Without this 'fix' it happens on both my adapters.

Backtrace (my own code, not the triangle example, using RUST_BACKTRACE=1):
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /usr/src/rustc-1.41.0/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: wgpu_core::command::render::<impl wgpu_core::hub::Global<G>>::command_encoder_run_render_pass
  10: wgpu_render_pass_end_pass
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: _ZN6scopes8try_mainEv
             at ../src/boot.cpp:320
  18: _ZN6scopes8run_mainEv
             at ../src/boot.cpp:348
  19: __libc_start_main
  20: _start
```

**Platform**
OS: Pop!_OS 19.10
Graphics info:
``` 
❯ lspci -k | grep -EA3  'VGA|Display'
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
	Subsystem: Dell HD Graphics 5500
	Kernel driver in use: i915
	Kernel modules: i915
--
04:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445]
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

**Comment by kvark** [comment]
It looks like your call stack doesn't have proper debug info: no line numbers. Could you maybe build a debug version of `wgpu-native` and share an update call stack?

**Comment by radgeRayden** [comment]
Sorry, here's the updated call stack:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /usr/src/rustc-1.41.0/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0:     0x7f13182cc8a3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4ef1f84901fa8edc
   1:     0x7f13182e2dbd - core::fmt::write::h026b5c0fa015f11c
   2:     0x7f13182cbd85 - std::io::Write::write_fmt::hc77e135d55d2160d
   3:     0x7f13182ce4be - std::panicking::default_hook::{{closure}}::h7a1ebe73b27c35f6
   4:     0x7f13182ce1d0 - std::panicking::default_hook::hc9a55f38c57244a0
   5:     0x7f13182ceb1b - std::panicking::rust_panic_with_hook::hd3ad4a665e641fa7
   6:     0x7f13182ce6ce - rust_begin_unwind
   7:     0x7f13182e7cbe - core::panicking::panic_fmt::he269dfe5481f7c47
   8:     0x7f13182e7c0a - core::panicking::panic::h31ff2e8d93dd669a
   9:     0x7f13180c4db8 - core::option::Option<T>::unwrap::h0c8a35ecc1ad7fd5
                               at /usr/src/rustc-1.41.0/src/libcore/macros/mod.rs:15
  10:     0x7f1318067ae2 - wgpu_core::command::render::<impl wgpu_core::hub::Global<G>>::command_encoder_run_render_pass::h57d579674fdc4ca1
                               at /home/radge/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/e2100b6/wgpu-core/src/command/render.rs:707
  11:     0x7f1317fd7486 - wgpu_render_pass_end_pass
                               at src/command.rs:97
  12:     0x7f1318613785 - <unknown>
  13:     0x7f13186120d1 - <unknown>
  14:     0x7f13186ff95d - <unknown>
  15:     0x7f13186cf294 - <unknown>
  16:     0x7f13186ceabe - <unknown>
  17:     0x7f13186ce07b - <unknown>
  18:     0x7f1319327acf - _ZN6scopes8try_mainEv
                               at ../src/boot.cpp:320
  19:     0x7f1319327c0c - _ZN6scopes8run_mainEv
                               at ../src/boot.cpp:348
  20:     0x7f131881f0b3 - __libc_start_main
  21:           0x40107e - _start
  22:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
fish: “env RUST_BACKTRACE=full scopes…” terminated by signal SIGABRT (Abort)
```

**Comment by kvark** [comment]
Thank you! The unwrap appears to be pointing at [this line](https://github.com/gfx-rs/wgpu/blob/e2100b6911168bf10d8543380681ebb4ca33b9b1/wgpu-core/src/command/render.rs#L707):
```rust
```

**Comment by radgeRayden** [comment]
> This can only happen if you are starting a render pass with no attachments...

Right, probably because I'm skipping the early exit on the check for `next_texture.view_id == 0` (on my test), and it proceeds with no texture. In the example such a case just prints an error and exits, so I'm afraid none of the two paths will give very meaningful information.

**Comment by kvark** [comment]
Today, you can't have a render pass with no attachments. And even if you could, this is not what your application expects anyway. You have to handle the case of `next_texture.view_id == 0` by waiting a bit and trying again, say in the next loop iteration. Given that we aren't hitting UB, and this is a safe panic, I'd say that there is no fix on our side required here.

**Comment by radgeRayden** [comment]
Thank you, simply skipping rendering of the frame seems to guarantee no failures on my test. May close the issue if appropriate.
